const constants = {
    API_STARTS: "API_STARTS",
    API_END: "API_END",
    SET_DEMOGRAPHIC_DETAILS: "SET_DEMOGRAPHIC_DETAILS",
    SET_ALLERGY_DETAILS: "SET_ALLERGY_DETAILS",
    SET_MEDICATION_DETAILS: "SET_MEDICATION_DETAILS",
    SET_PROVIDER_DETAILS: "SET_PROVIDER_DETAILS",
    SET_M3PRESCRIPTION_DETAILS: "SET_M3PRESCRIPTION_DETAILS",
    NOT_FOUND: "NOT_FOUND",
    ROOT_URL:  "http://localhost:5000",
    ETH_ADDRESS: "0x1daa654cfbc28f375e0f08f329de219fff50c765"
}

export default constants;